// eslint-disable-next-line @nx/enforce-module-boundaries, import/no-unresolved
import { NextTamaguiProvider } from '@my-project/shared/ui/ui-kit';
import './global.css';

export const metadata = {
  title: 'Welcome to web',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body>
        <NextTamaguiProvider>{children}</NextTamaguiProvider>
      </body>
    </html>
  );
}
